apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service-beta
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: nginx-app